### ISSUE TITLE
crypto.createCipher deprecated

### ISSUE THREAD

**Issue by fturiot** [bin-y/standard-ecies#2]
we must use crypto.createCipheriv instead

**Comment by bin-y** [comment]
Hi, thanks for your feedback.
Happy to know that there are still real world users exist.
I thought nobody is using this library thus abandoned this repo for a long time.
I will address this issue in recent.

**Comment by bin-y** [comment]
Using crypto.createCipher / crypto.createDecipher is reasonable in certain scenarios because the function it self does not make a system unsafe. However, since it is deprecated by nodejs, I made some change to avoid using them by default. But users of this library can still use old crypto.createCipher if they need. This issue should have fixed in version 2.0.0.
