### ISSUE TITLE
How to get to JWE

### ISSUE THREAD

**Issue by OR13** [bin-y/standard-ecies#4]
This package is awesome!

I'm interested in building JWE interoperability between a module that takes this package as a dependency and https://github.com/panva/jose

Mostly to better understand how to get JWE from lower level cryptographic primitives... wondering if you are aware of any existing work in this area?

If you are not, feel free to state so and close this issue as off-topic.

**Comment by bin-y** [comment]
I didn't know JWE before, but I read some documents after read your question and here is what I got.

Unfortunately, according to [rfc7516 4.1.1](https://tools.ietf.org/html/rfc7516#section-4.1.1), [rfc7515 4.1.1](https://tools.ietf.org/html/rfc7515#section-4.1.1), and [rfc7518 3.1](https://tools.ietf.org/html/rfc7518#section-3.1). ECIES is not supported by JWE/JWA by default, you need to build your own implementation to add that algorithm if the jose library didn't support registering algorithm as a custom JWA.

But if you are not thinking about make this library registered as a JWA to your JWE library, here are simple solutions that seem to work. 

You can create a crypto.ECDH object from [aforementioned jose library](https://github.com/panva/jose/blob/master/lib/jwa/ecdh/compute_secret.js#L37) and use it to this library. But I'm not sure what is improvedDH of that library. 

If you want to use improvedDH  of that library. Since my library only relies on generateKeys/getPublickey/setPrivateKey of crypto.ECDH module and aforementioned jose library have implemented [ECDH](https://github.com/panva/jose/blob/a2d428e5e0a4021eea5ba9ff0fbfad51cb93d60e/test/cookbook/rfc8037.ecdhes.test.js) and key importing/exporting. You can create a warper class between crypto.ECDH and jose's ECDH, and I can add a option field to support custom ecdh implementation to this library.

**Comment by OR13** [comment]
@bin-y thanks you can close this issue whenever you like.

**Comment by bin-y** [comment]
Okay, you can create a new issue/pr if you need this library to support custom ECDH implementation.
